Created basic structure of components
Red-Warrior/stellar-burger pull request #1
Opened 2023-04-15 22:39 UTC by Red-Warrior

2023-04-16 04:14 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно убрать обводку у блоков, эта обводка на макете нужна только что бы сделать описание поясняющее к этому блоку;

- В компоненте App-header требуется поправить семантику, переделать button в ссылки;

- По макету у булок должна быть приписка `(верх)` и `(низ)`;

- нужно описать PropTypes для всех компонентов, где используются пропсы.

  Необходимо полное описание ингредиента, А также нужно указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  // для множества ингредиентов
  ingredients: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;

  // для 1 ингредиента
  ingredient: ingredientTypes.isRequired;
  ```

  Проверьте во всём проекте.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

### **Сделает код лучше:**

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +const url = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить:**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +      });
**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/app-header/app-header.jsx
> +  });
**Надо исправить:**

в шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, не нужно сейчас это делать через стейт

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  const totalPrice = currentMain.reduce((acc, item) => acc + item.price, 0);
**Надо исправить:**

сейчас цена считается неправильно, вы не учитываете, что ещё есть 2 булки.

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    ingredientsSets.main[rand(ingredientsSets.main.length - 1)]);
**Надо исправить:**

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, otherIngredients } = {
  bun: ingredients.find(item => item.type === 'bun'),
  otherIngredients: ingredients.filter(item => item.type !== 'bun'),
};
```

По поводу рандомных ингредиентов, давайте оставим всё как есть, и не будем обрезать ингредиенты, это всё вы сделаете на редаксе в 3 спринте.

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +          text={currentBun.name}
**Надо исправить:**

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +const BurgerConstructor = ({ingredients}) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +const BurgerIngredients = ({ingredients}) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }]
**Можно лучше:**

лучше вынести за пределы компонента.

2023-04-16 04:14 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          Object.keys(titles).map((section) => (
**Можно лучше:**

`section` лучше переименовать в `type`

**Надо исправить:**

Вместо `titles`, вам нужно использовать `ingredientsSets`.

2023-04-16 04:14 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, {})
**Можно лучше:**

а почему бы сразу не сделать вот такой объект, вместо menuTitles: 

```js

const titles = {
  bun: "Булки",
  sauce: "Соусы",
  main: "Начинки",
}

```

2023-04-16 04:14 UTC, ArslanDev666 commented on src/components/button-header/button-header.jsx
> +const ButtonHeader = (
**Можно лучше:**

Лучше перенести компонент в папку `app-header/components/link`, а также переименовать, т.к. это всё же будет ссылка, а не кнопка.

**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-04-16 04:14 UTC, ArslanDev666 commented on src/components/card/card.jsx
> +const Card = ({ingredient}) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes. А также лучше переименовать в `IngredientCard`, не забудьте переименовать папку тоже.

2023-04-16 04:14 UTC, ArslanDev666 commented on src/components/collection/collection.jsx
> +const Collection = ({title, ingredients}) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

Лучше переименовать в `IngredientsCategory`

2023-04-16 04:14 UTC, ArslanDev666 commented on src/components/ingredients-menu/ingredients-menu.jsx
> +const IngredientsMenu = ({menuTitles, extraClass}) => {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

Лучше переименовать в `IngredientsTabs`.

2023-04-16 04:14 UTC, ArslanDev666 commented on src/components/button-header/button-header.jsx
> +      style={{border: "1px solid deeppink"}}
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-04-17 18:25 UTC, Red-Warrior commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }]
Например, куда?

2023-04-19 08:32 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }]
Просто за пределы компонента, 
 
 ```js
const menuTitles = [...];

const Component = () => {...}
```

2023-04-19 08:34 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Некоторые замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- Нужно убрать обводку у блоков, эта обводка на макете нужна только что бы сделать описание поясняющее к этому блоку;

- В компоненте App-header требуется поправить семантику, переделать button в ссылки;

- нужно описать PropTypes для всех компонентов, где используются пропсы.

  Необходимо полное описание ингредиента, А также нужно указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  // для множества ингредиентов
  ingredients: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;

  // для 1 ингредиента
  ingredient: ingredientTypes.isRequired;
  ```

  Проверьте во всём проекте.

- Не исправлены замечания:

  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167690212>
  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167688119>
  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167688636>

    под словами `давайте оставим всё как есть`, я имел ввиду, то, что не нужно сейчас делать рандом ингредиентов. Лучше просто написать

    ```js
    const { bun, otherIngredients } = {
      bun: ingredients.find((item) => item.type === "bun"),
      otherIngredients: ingredients.filter((item) => item.type !== "bun"),
    };
    ```

  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167688734>;
  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167688753>;
  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167689450>;
  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167689571>;
  - <https://github.com/Red-Warrior/stellar-burger/pull/1#discussion_r1167689618>;

2023-04-22 13:21 UTC, merged